# File: manual-azure-pipeline.yml

# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: 'Manual Pipeline'
resources:
  repositories:
    - repository: template-scripts
      type: github
      name: dmedeiros-veracode/devops-scripts-azure-devops
      endpoint: dmedeiros-veracode

trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

stages: 
- stage: Build
        
  jobs:
  - job: Build_Debug
    displayName: Debug Build
  
    steps:
    - template: steps/abstract-build-steps.yml@template-scripts
      parameters:
        buildConfiguration: 'Debug'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.StagingDirectory)\WebApp.zip 
        artifactName: WebApp_Debug

- stage: Security_Testing
  jobs:       
  - template: jobs/veracode-sast-pipeline-job.yml@template-scripts
    parameters: 
      downloadArtifact: "WebApp_Debug"
      
  - job: SCA_Security_Testing
    displayName: Software Componsition Analysis Testing
  
    steps:
    - bash: echo 'SCA Testing'
    - bash: echo 'Downloading Project'
    
# Deployment Stage of CI/CD Pipeline
# - stage: Deployment

#  jobs:
#   - job: Release_Deployment
#     displayName: Release Deployment
   
#     steps:
#     - bash: echo 'Release Deployed'
